### ISSUE TITLE
Crash while looking at Crafting Terminal[From appliedenergistics2-rv6-stable-6.jar]

### ISSUE THREAD

**Issue by ahdg6** [mccreery/better-hud#58] opened 2019-04-14 08:33 UTC
Crash while looking at Crafting Terminal[From appliedenergistics2-rv6-stable-6.jar]  
If there are no [waila and wawla],the game will crash when I use it
May be it's because of the update [Option to disable writing NBT data in block viewer]
it won't be happen at [1.4-beta.3]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/14/19 3:58 PM
Description: Unexpected error

java.lang.StackOverflowError: Unexpected error
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:557)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)at 
        at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1492002432 bytes (1422 MB) / 1979711488 bytes (1888 MB) up to 4227858432 bytes (4032 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4028m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2824 Optifine OptiFine_1.12.2_HD_U_E4_pre1 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                   | Signature                                |
	|:------ |:------------------- |:------------ |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                            | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                            | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2824.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2824 | forge-1.12.2-14.23.5.2824.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | appliedenergistics2 | rv6-stable-6 | (G1)appliedenergistics2-rv6-stable-6.jar | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | betterhud           | 1.4          | (T)Betterhud-1.12.2-1.4.jar              | None                                     |
	| LCHIJA | waila               | 1.8.26       | (T)Hwyla-1.8.26-B41_1.12.2.jar           | None                                     |
	| LCHIJA | wawla               | 2.5.269      | (T)Wawla-1.12.2-2.5.269.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |

**Comment by mccreery** [comment] 2019-04-14 16:15
Duplicate of #57. Enabling the option you mentioned should fix the crash.

**Closed by mccreery** 2019-04-14 16:15 UTC
