### ISSUE TITLE
Pick Up Count Crash?

### ISSUE THREAD

**Issue by Fortist** [mccreery/better-hud#52] opened 2019-02-14 11:12 UTC
Using Beta 4, I was in a small 2x1 pool of water and dug some dirt and got this crash.
Dont know if it has to do with it but I am also using a mod called "Better Diving"

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2019-02-14 00:07:22 EST
Description: Unexpected error

java.lang.IndexOutOfBoundsException
    at java.util.concurrent.CopyOnWriteArrayList.subList(Unknown Source)
    at jobicade.betterhud.render.Grid.flatten(Grid.java:42)
    at jobicade.betterhud.render.Grid.render(Grid.java:140)
    at jobicade.betterhud.element.PickupCount.render(PickupCount.java:138)
    at jobicade.betterhud.element.HudElement.tryRender(HudElement.java:268)
    at jobicade.betterhud.element.HudElement.renderAll(HudElement.java:284)
    at jobicade.betterhud.events.RenderEvents.renderOverlay(RenderEvents.java:150)
    at jobicade.betterhud.events.RenderEvents.onRenderTick(RenderEvents.java:66)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2777_RenderEvents_onRenderTick_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:119)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by mccreery** [comment] 2019-04-04 14:55
Duplicate of #54 (oops, this one was created earlier)

**Closed by mccreery** 2019-04-04 14:55 UTC
