### ISSUE TITLE
Rendering error with health bar

### ISSUE THREAD

**Issue by Andyghandi** [mccreery/better-hud#30] opened 2018-10-04 19:34 UTC
Using latest forge for 1.12.2 and latest version of this mod causes some weird bugs with the health bar, rendering just green or white, and is misplaced, with no way of moving it around. See the attachment. 

![2018-10-04_21 27 56](https://user-images.githubusercontent.com/25442543/46498192-02b7b200-c81d-11e8-92c0-cd0ec3e7f480.png)
![2018-10-04_21 28 36](https://user-images.githubusercontent.com/25442543/46498193-02b7b200-c81d-11e8-8d5a-d5c845a0f1a5.png)

**Comment by mccreery** [comment] 2018-10-05 09:43
Do you have any other mods installed that change the health bar? It looks like another mod is cancelling the event and rendering their own bar in the vanilla position.

**Comment by Andyghandi** [comment] 2018-10-05 10:56
I use a bunch of mods, none really adding much things to the GUI. To my knowledge, nothing changes the health and armor gui. And there is not really anything popping up in the game log file

**Comment by Andyghandi** [comment] 2018-10-05 10:57
I can try locating the problem by uninstalling mods, one by one, but that will take time as my modpack takes 10 mins to launch each time. 250 mods installed.

**Comment by mccreery** [comment] 2018-10-05 13:16
Another option would be to start with a base Forge installation and add mods one at a time, or test each mod individually. It may be difficult to figure out the culprit(s), because it could be any combination of mods, but it's most likely just one. I have never seen this problem myself, and as far as I know, Better HUD should reset at least the colour and texture before drawing.

**Comment by mccreery** [comment] 2019-01-16 14:02
this issue may have been fixed by [v1.12.2-1.4-beta.2](https://minecraft.curseforge.com/projects/better-hud/files/2660769). Please notify me if so, so I can close this issue.

**Comment by TheCorruption** [comment] 2019-02-02 05:13
I found what is likely the same issue. It is caused by Mantle, and has not been fixed as of beta 3.

**Comment by mccreery** [comment] 2019-02-02 16:00
I can't reproduce this with just Better HUD and Mantle, are you sure?

**Comment by DPattee** [comment] 2019-02-03 18:09
The 'misplaced' aspect I can reproduce with Beta 3.

Repro steps are:
1) Have health, armor, food, and experience bar all Enabled
2) Disable the experience bar
3) Note that Armor and Food move downward closer to the Hotbar, but the Health bar does not move - so now Armor is slightly overlapping it.

**Comment by mccreery** [comment] 2019-02-04 02:18
@DPattee The issue is confirmed a problem with Mantle, I have opened an issue there.

**Comment by mccreery** [comment] 2020-05-21 22:33
Closing since the issue is solved in Mantle. If this issue occurs again, please leave a comment and I'll reopen.

**Closed by mccreery** 2020-05-21 22:33 UTC
